"""
SM-Aware Kernel Generator.

AI agent that generates Triton kernels with SM-aware optimization.
Uses wave efficiency analysis to guide config selection.
"""

import os
import json
import time
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field

from .workload import compute_wave_efficiency, suggest_optimal_block_size, SM_COUNTS


@dataclass
class TritonConfig:
    """Triton autotune configuration."""
    block_m: int
    block_n: int
    block_k: int
    group_size_m: int = 8
    num_stages: int = 3
    num_warps: int = 4

    def to_triton_config(self):
        """Convert to triton.Config dict."""
        return {
            'BLOCK_SIZE_M': self.block_m,
            'BLOCK_SIZE_N': self.block_n,
            'BLOCK_SIZE_K': self.block_k,
            'GROUP_SIZE_M': self.group_size_m,
        }

    def __str__(self) -> str:
        return f"M={self.block_m},N={self.block_n},K={self.block_k},G={self.group_size_m}"


# Pre-defined config candidates for different SM regimes
CONFIGS_LOW_SM = [
    # Small tiles for few SMs → more blocks to fill waves
    TritonConfig(16, 32, 32, group_size_m=4, num_warps=2),
    TritonConfig(16, 64, 32, group_size_m=4, num_warps=2),
    TritonConfig(32, 32, 32, group_size_m=4, num_warps=4),
    TritonConfig(32, 64, 32, group_size_m=8, num_warps=4),
    TritonConfig(32, 128, 32, group_size_m=8, num_warps=4),
]

CONFIGS_MID_SM = [
    # Medium tiles for moderate SM counts
    TritonConfig(32, 64, 32, group_size_m=8, num_warps=4),
    TritonConfig(64, 64, 32, group_size_m=8, num_warps=4),
    TritonConfig(64, 128, 32, group_size_m=8, num_warps=4),
    TritonConfig(64, 128, 64, group_size_m=8, num_warps=4),
    TritonConfig(128, 64, 32, group_size_m=8, num_warps=4),
    TritonConfig(128, 64, 64, group_size_m=8, num_warps=4),
]

CONFIGS_HIGH_SM = [
    # Large tiles for many SMs → better L2 reuse
    TritonConfig(64, 128, 64, group_size_m=8, num_warps=4),
    TritonConfig(128, 64, 64, group_size_m=8, num_warps=4),
    TritonConfig(128, 128, 32, group_size_m=8, num_warps=4),
    TritonConfig(128, 128, 64, group_size_m=8, num_warps=8),
    TritonConfig(128, 256, 64, group_size_m=8, num_warps=8),
    TritonConfig(128, 256, 128, group_size_m=8, num_warps=8),
    TritonConfig(256, 128, 64, group_size_m=8, num_warps=8),
]


def get_configs_for_sm(num_sms: int) -> List[TritonConfig]:
    """Get appropriate config candidates for given SM count."""
    if num_sms <= 24:
        return CONFIGS_LOW_SM + CONFIGS_MID_SM[:2]
    elif num_sms <= 64:
        return CONFIGS_MID_SM + CONFIGS_HIGH_SM[:2]
    else:
        return CONFIGS_HIGH_SM + CONFIGS_MID_SM


def generate_sm_aware_kernel(
    M: int, N: int, K: int,
    num_sms: int,
    dtype: str = "float16",
    configs: List[TritonConfig] = None,
) -> str:
    """
    Generate SM-aware Triton GEMM kernel code.

    Args:
        M, N, K: Matrix dimensions
        num_sms: SM partition size
        dtype: Data type
        configs: Custom config list (if None, auto-select)

    Returns:
        Python code string
    """
    if configs is None:
        configs = get_configs_for_sm(num_sms)

    # Analyze wave efficiency for each config
    config_analysis = []
    for cfg in configs:
        metrics = compute_wave_efficiency(M, N, cfg.block_m, cfg.block_n, num_sms)
        config_analysis.append((cfg, metrics))

    # Sort by wave efficiency
    config_analysis.sort(key=lambda x: (-x[1]["overall_efficiency"], x[1]["num_waves"]))

    # Build config strings
    config_strs = []
    for cfg, metrics in config_analysis:
        config_strs.append(
            f"    triton.Config({{\n"
            f"        'BLOCK_SIZE_M': {cfg.block_m},\n"
            f"        'BLOCK_SIZE_N': {cfg.block_n},\n"
            f"        'BLOCK_SIZE_K': {cfg.block_k},\n"
            f"        'GROUP_SIZE_M': {cfg.group_size_m},\n"
            f"    }}, num_stages={cfg.num_stages}, num_warps={cfg.num_warps}),"
        )

    configs_code = "\n".join(config_strs)

    # Wave efficiency comment
    best_cfg, best_metrics = config_analysis[0]
    wave_comment = f"# Best config: {best_cfg}, efficiency: {best_metrics['overall_efficiency']*100:.1f}%"

    kernel_code = f'''"""
SM-Aware GEMM Kernel for M={M}, N={N}, K={K} with {num_sms} SMs.

Generated by ElastiKernel SM-Aware Agent.
{wave_comment}
"""

import torch
import triton
import triton.language as tl


def get_configs():
    """Return SM-optimized configs for {num_sms} SMs."""
    return [
{configs_code}
    ]


@triton.autotune(
    configs=get_configs(),
    key=['M', 'N', 'K', 'NUM_SMS'],
)
@triton.jit
def gemm_kernel(
    # Pointers
    a_ptr, b_ptr, c_ptr,
    # Dimensions
    M, N, K,
    # Strides
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    # Block sizes (constexpr)
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
    # SM count for autotune key (not used in kernel body)
    NUM_SMS: tl.constexpr,
):
    """
    SM-aware GEMM kernel.

    NUM_SMS is in autotune key to force re-tuning for different SM counts.
    The kernel body is unchanged - optimization comes from config selection.
    """
    # Block indices
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BLOCK_SIZE_M)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)
    num_pid_in_group = GROUP_SIZE_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_SIZE_M
    group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
    pid_m = first_pid_m + (pid % num_pid_in_group) % group_size_m
    pid_n = (pid % num_pid_in_group) // group_size_m

    # Pointers for block
    offs_am = (pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)) % M
    offs_bn = (pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)) % N
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    a_ptrs = a_ptr + (offs_am[:, None] * stride_am + offs_k[None, :] * stride_ak)
    b_ptrs = b_ptr + (offs_k[:, None] * stride_bk + offs_bn[None, :] * stride_bn)

    # Accumulator
    acc = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)

    # K-loop
    k_loops = tl.cdiv(K, BLOCK_SIZE_K)
    for k in range(k_loops):
        # Load tiles with boundary masking
        a = tl.load(a_ptrs, mask=offs_k[None, :] < K - k * BLOCK_SIZE_K, other=0.0)
        b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k * BLOCK_SIZE_K, other=0.0)

        # Matrix multiply accumulate
        acc = tl.dot(a, b, acc)

        # Advance pointers
        a_ptrs += BLOCK_SIZE_K * stride_ak
        b_ptrs += BLOCK_SIZE_K * stride_bk

    # Store result
    c = acc.to(tl.{dtype})
    offs_cm = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_cn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs = c_ptr + stride_cm * offs_cm[:, None] + stride_cn * offs_cn[None, :]
    c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < N)
    tl.store(c_ptrs, c, mask=c_mask)


def run(A: torch.Tensor, B: torch.Tensor, C: torch.Tensor,
        M: int, N: int, K: int, NUM_SMS: int) -> None:
    """Entry point for FlashInfer-Bench compatibility."""
    # Determine device
    device = A.device

    # Grid function
    def grid(META):
        return (triton.cdiv(M, META['BLOCK_SIZE_M']) * triton.cdiv(N, META['BLOCK_SIZE_N']),)

    # Launch kernel
    gemm_kernel[grid](
        A, B, C,
        M, N, K,
        A.stride(0), A.stride(1),
        B.stride(0), B.stride(1),
        C.stride(0), C.stride(1),
        NUM_SMS=NUM_SMS,
    )


def benchmark(A: torch.Tensor, B: torch.Tensor, num_sms: int = 108) -> torch.Tensor:
    """Convenience function for standalone benchmarking."""
    M, K = A.shape
    _, N = B.shape
    C = torch.empty((M, N), device=A.device, dtype=A.dtype)
    run(A, B, C, M, N, K, num_sms)
    return C


if __name__ == "__main__":
    # Quick test
    torch.manual_seed(42)
    M, N, K = {M}, {N}, {K}
    NUM_SMS = {num_sms}

    A = torch.randn((M, K), device="cuda", dtype=torch.{dtype})
    B = torch.randn((K, N), device="cuda", dtype=torch.{dtype})

    # Warmup
    C = benchmark(A, B, NUM_SMS)
    torch.cuda.synchronize()

    # Benchmark
    import time
    start = time.time()
    for _ in range(10):
        C = benchmark(A, B, NUM_SMS)
    torch.cuda.synchronize()
    elapsed = time.time() - start

    # Verify
    ref = torch.matmul(A, B)
    max_err = (C - ref).abs().max().item()

    print(f"M={M}, N={N}, K={K}, SMs={NUM_SMS}")
    print(f"Latency: {{elapsed*1000/10:.2f}} ms")
    print(f"Max error: {{max_err:.2e}}")
'''
    return kernel_code


class SMAwareKernelGenerator:
    """
    AI-driven SM-aware kernel generator.

    Generates and iteratively optimizes Triton kernels for different
    SM partition sizes using wave efficiency analysis.
    """

    def __init__(
        self,
        model_name: str = "gpt-4",
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
    ):
        self.model_name = model_name
        self.api_key = api_key or os.getenv("LLM_API_KEY")
        self.base_url = base_url

        if self.api_key is None:
            print("Warning: No API key set. Use generate_sm_aware_kernel() for rule-based generation.")

    def generate(
        self,
        M: int, N: int, K: int,
        num_sms: int,
        use_ai: bool = True,
    ) -> str:
        """
        Generate kernel code.

        Args:
            M, N, K: Matrix dimensions
            num_sms: SM partition size
            use_ai: If True and API key available, use LLM. Otherwise use rule-based.

        Returns:
            Python kernel code string
        """
        if not use_ai or self.api_key is None:
            return generate_sm_aware_kernel(M, N, K, num_sms)

        # AI generation path (similar to FlashInfer-Bench)
        try:
            import openai
            client = openai.OpenAI(api_key=self.api_key, base_url=self.base_url)

            prompt = self._build_prompt(M, N, K, num_sms)
            response = client.chat.completions.create(
                model=self.model_name,
                messages=[{"role": "user", "content": prompt}],
            )
            code = response.choices[0].message.content

            # Clean code
            code = self._clean_code(code)
            return code

        except ImportError:
            print("openai not installed, falling back to rule-based")
            return generate_sm_aware_kernel(M, N, K, num_sms)

    def _build_prompt(self, M: int, N: int, K: int, num_sms: int) -> str:
        """Build prompt for LLM kernel generation."""
        best_cfg = suggest_optimal_block_size(M, N, num_sms)
        wave_info = f"Best block size: {best_cfg[0]}x{best_cfg[1]}, efficiency: {best_cfg[2]['overall_efficiency']*100:.1f}%"

        return f"""Generate a Triton GEMM kernel optimized for wave efficiency.

## Task
- Operation: C = A @ B where A is {M}x{K}, B is {K}x{N}
- Target SM count: {num_sms}
- Data type: float16

## SM-Aware Optimization Critical Points

1. **Add NUM_SMS to autotune key**: `key=['M', 'N', 'K', 'NUM_SMS']`
2. **Pass NUM_SMS as tl.constexpr**: It forces Triton to re-tune for each SM count
3. **Wave Efficiency Analysis**: {wave_info}

## Wave Quantization Problem
- Blocks = ceil(M/BLOCK_M) × ceil(N/BLOCK_N)
- Waves = ceil(Blocks / NUM_SMS)
- Last wave often has idle SMs

## Config Strategy for {num_sms} SMs
- Choose BLOCK_M × BLOCK_N such that Blocks ≈ k × NUM_SMS for some integer k
- Smaller blocks = more blocks = better wave fill (but more overhead)
- Larger blocks = fewer blocks = better L2 reuse (but risk wave waste)

## Requirements
- Use `@triton.autotune` with multiple configs
- Include NUM_SMS in autotune key
- Provide `run(A, B, C, M, N, K, NUM_SMS)` entry point
- Handle boundary masking properly
- Match torch.matmul reference

Generate the complete kernel code:
"""

    def _clean_code(self, code: str) -> str:
        """Clean generated code."""
        # Remove markdown code blocks
        if "```python" in code:
            code = code.split("```python")[1]
        if "```" in code:
            code = code.split("```")[0]
        return code.strip()


if __name__ == "__main__":
    # Test generator
    code = generate_sm_aware_kernel(4096, 4096, 4096, 32)
    print(code[:1000] + "...")
    print(f"\nTotal length: {len(code)} chars")
